-- 코드 11-7 src/main/resources/db/migration/V1__init.sql

DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(255) not null,
    last_name varchar(255) not null
);

insert into PERSON (last_name, first_name) values ('이', '일웅');
